#import "./channelFragment.gql"
#import "./messageFragment.gql"

query channel ($id: String!) {
  channelById (id: $id) {
    ...channel
    messagesByChannelId {
      nodes {
        ...message
      }
    }
  }
}
