#import "./messageFragment.gql"

fragment messageNullable on MessageNullable {
  id
  channelId
  userId
  content
  dateAdded
  dateUpdated
}
subscription messageChanged ($channelId: String!) {
  messageChanged (channelId: $channelId) {
    type
    message {
      ...message
    }
    oldrec {
      ...messageNullable
    }
  }
}
